description = "A builder based on paketo-buildpacks/go"

[[buildpacks]]
  id = "io.avarteqgmbh.buildpacks.git-ssh"
  version = "0.5.7"
  uri = "docker://docker.io/anyninesgmbh/git-ssh-buildpack:0.5.7"

[[buildpacks]]
  id = "anynines/gitcredentials"
  version = "0.0.18"
  uri = "docker://docker.io/anyninesgmbh/gitcredentials:0.0.18"

[[buildpacks]]
  id = "paketo-buildpacks/ca-certificates"
  version = "3.6.8"
  uri = "docker://docker.io/paketo-buildpacks/ca-certificates:3.6.8"

[[buildpacks]]
  id = "paketo-buildpacks/watchexec"
  version = "2.9.0"
  uri = "docker://docker.io/paketo-buildpacks/watchexec:2.9.0"

[[buildpacks]]
  id = "paketo-buildpacks/go-dist"
  version = "2.5.0"
  uri = "docker://docker.io/paketo-buildpacks/go-dist:2.5.0"

[[buildpacks]]
  id = "paketo-buildpacks/git"
  version = "1.0.8"
  uri = "docker://docker.io/paketo-buildpacks/git:1.0.8"

[[buildpacks]]
  id = "paketo-buildpacks/go-mod-vendor"
  version = "1.0.29"
  uri = "docker://docker.io/paketo-buildpacks/go-mod-vendor:1.0.29"

[[buildpacks]]
  id = "paketo-buildpacks/go-build"
  version = "2.2.1"
  uri = "docker://docker.io/paketo-buildpacks/go-build:2.2.1"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  version = "5.6.9"
  uri = "docker://docker.io/paketo-buildpacks/procfile:5.6.9"

[[buildpacks]]
  id = "paketo-buildpacks/environment-variables"
  version = "4.5.7"
  uri = "docker://docker.io/paketo-buildpacks/environment-variables:4.5.7"

[[buildpacks]]
  id = "paketo-buildpacks/image-labels"
  version = "4.5.6"
  uri = "docker://docker.io/paketo-buildpacks/image-labels:4.5.6"

[[buildpacks]]
  id = "paketo-buildpacks/ca-certificates"
  version = "3.6.8"
  uri = "docker://docker.io/paketo-buildpacks/ca-certificates:3.6.8"

[[buildpacks]]
  id = "paketo-buildpacks/watchexec"
  version = "2.9.0"
  uri = "docker://docker.io/paketo-buildpacks/watchexec:2.9.0"

[[buildpacks]]
  id = "paketo-buildpacks/go-dist"
  version = "2.5.0"
  uri = "docker://docker.io/paketo-buildpacks/go-dist:2.5.0"

[[buildpacks]]
  id = "paketo-buildpacks/git"
  version = "1.0.8"
  uri = "docker://docker.io/paketo-buildpacks/git:1.0.8"

[[buildpacks]]
  id = "paketo-buildpacks/go-build"
  version = "2.2.1"
  uri = "docker://docker.io/paketo-buildpacks/go-build:2.2.1"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  version = "5.6.9"
  uri = "docker://docker.io/paketo-buildpacks/procfile:5.6.9"

[[buildpacks]]
  id = "paketo-buildpacks/environment-variables"
  version = "4.5.7"
  uri = "docker://docker.io/paketo-buildpacks/environment-variables:4.5.7"

[[buildpacks]]
  id = "paketo-buildpacks/image-labels"
  version = "4.5.6"
  uri = "docker://docker.io/paketo-buildpacks/image-labels:4.5.6"

[[order]]
  [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true
    version = "0.5.7"

  [[order.group]]
    id = "anynines/gitcredentials"
    optional = true
    version = "0.0.18"

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.8"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.9.0"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.5.0"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.0.8"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "1.0.29"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "2.2.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.9"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.7"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

[[order]]
  [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true
    version = "0.5.7"

  [[order.group]]
    id = "anynines/gitcredentials"
    optional = true
    version = "0.0.18"

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.8"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.9.0"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.5.0"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.0.8"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "2.2.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.9"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.7"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.6"

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "anyninesgmbh/stack-jammy-build:0.2.0-cnb"
  run-image = "anyninesgmbh/stack-jammy-run:0.2.0-cnb"
