name: arm64-buildpack

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ARM64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Image
        run: sudo docker build ./stack -t dashaun/stack-run:focal --target run --build-arg STACK_ID="20220531"

      - name: Build Image
        run: sudo docker build ./stack -t dashaun/stack-build:focal --target build --build-arg STACK_ID="20220531"

      - name: git setup
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          name: 'DaShaun'
          email: 'dashaun@dashaun.com'
          actor: 'dashaun'
      - run: ./scripts/clone.sh paketo-buildpacks/bellsoft-liberica-arm64 9.3.5
